### ISSUE TITLE
提供安裝環境

### ISSUE THREAD

**Issue by ken19980727** [AUSTIN2526/iThome2023-learn-NLP-in-30-days#1]
大大你好

可以請你提供一下這些教學的package version嗎

**Comment by AUSTIN2526** [comment]
您好，這份專案主要為一篇NLP的教學文章，由於每一章節所需的package可能會有所不同，因此我難以一一列出所有的package版本。您可以參照[每篇教學文章](https://ithelp.ithome.com.tw/users/20152236/ironman/6669)的環境配置方式，在每篇教學中我都有列出需特別注意的安裝環境和方式。但因本專案是在急迫的時間內完成，導致內容中有許多錯誤與程式碼的撰寫與規劃尚未完善，今年出版書籍時會將此問題修正。如果您在安裝或操作過程中有任何疑問，請隨時向我提出。

祝您學習愉快，謝謝!
